%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(report_proto).
-define(report_proto, true).

-define(report_proto_gpb_version, "3.26.4").

-ifndef('SERVERINFO_PB_H').
-define('SERVERINFO_PB_H', true).
-record('ServerInfo',
        {serverType             :: binary() | iolist() | undefined, % = 1
         serverID               :: binary() | iolist() | undefined, % = 2
         serverURI              :: binary() | iolist() | undefined, % = 3
         max                    :: integer() | undefined % = 4, 32 bits
        }).
-endif.

-endif.
