// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package glib

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestMsg struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMsg) Reset()         { *m = TestMsg{} }
func (m *TestMsg) String() string { return proto.CompactTextString(m) }
func (*TestMsg) ProtoMessage()    {}
func (*TestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *TestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMsg.Unmarshal(m, b)
}
func (m *TestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMsg.Marshal(b, m, deterministic)
}
func (m *TestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMsg.Merge(m, src)
}
func (m *TestMsg) XXX_Size() int {
	return xxx_messageInfo_TestMsg.Size(m)
}
func (m *TestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TestMsg proto.InternalMessageInfo

func (m *TestMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TestMsg) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *TestMsg) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type Login struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Uuid                 int32    `protobuf:"varint,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Login) GetUuid() int32 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

// aes 加密
type AesEncode struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AesEncode) Reset()         { *m = AesEncode{} }
func (m *AesEncode) String() string { return proto.CompactTextString(m) }
func (*AesEncode) ProtoMessage()    {}
func (*AesEncode) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *AesEncode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AesEncode.Unmarshal(m, b)
}
func (m *AesEncode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AesEncode.Marshal(b, m, deterministic)
}
func (m *AesEncode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AesEncode.Merge(m, src)
}
func (m *AesEncode) XXX_Size() int {
	return xxx_messageInfo_AesEncode.Size(m)
}
func (m *AesEncode) XXX_DiscardUnknown() {
	xxx_messageInfo_AesEncode.DiscardUnknown(m)
}

var xxx_messageInfo_AesEncode proto.InternalMessageInfo

func (m *AesEncode) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AesEncode) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

// aes 解密
type AesDecode struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AesDecode) Reset()         { *m = AesDecode{} }
func (m *AesDecode) String() string { return proto.CompactTextString(m) }
func (*AesDecode) ProtoMessage()    {}
func (*AesDecode) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *AesDecode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AesDecode.Unmarshal(m, b)
}
func (m *AesDecode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AesDecode.Marshal(b, m, deterministic)
}
func (m *AesDecode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AesDecode.Merge(m, src)
}
func (m *AesDecode) XXX_Size() int {
	return xxx_messageInfo_AesDecode.Size(m)
}
func (m *AesDecode) XXX_DiscardUnknown() {
	xxx_messageInfo_AesDecode.DiscardUnknown(m)
}

var xxx_messageInfo_AesDecode proto.InternalMessageInfo

func (m *AesDecode) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AesDecode) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

// aes 解密回复
type AesDecodeReply struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reply                string   `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AesDecodeReply) Reset()         { *m = AesDecodeReply{} }
func (m *AesDecodeReply) String() string { return proto.CompactTextString(m) }
func (*AesDecodeReply) ProtoMessage()    {}
func (*AesDecodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *AesDecodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AesDecodeReply.Unmarshal(m, b)
}
func (m *AesDecodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AesDecodeReply.Marshal(b, m, deterministic)
}
func (m *AesDecodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AesDecodeReply.Merge(m, src)
}
func (m *AesDecodeReply) XXX_Size() int {
	return xxx_messageInfo_AesDecodeReply.Size(m)
}
func (m *AesDecodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AesDecodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_AesDecodeReply proto.InternalMessageInfo

func (m *AesDecodeReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AesDecodeReply) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

type Payload struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Pack                 []byte   `protobuf:"bytes,2,opt,name=pack,proto3" json:"pack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Payload) GetPack() []byte {
	if m != nil {
		return m.Pack
	}
	return nil
}

type RpcPackage struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Cmd                  int32    `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcPackage) Reset()         { *m = RpcPackage{} }
func (m *RpcPackage) String() string { return proto.CompactTextString(m) }
func (*RpcPackage) ProtoMessage()    {}
func (*RpcPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *RpcPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcPackage.Unmarshal(m, b)
}
func (m *RpcPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcPackage.Marshal(b, m, deterministic)
}
func (m *RpcPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcPackage.Merge(m, src)
}
func (m *RpcPackage) XXX_Size() int {
	return xxx_messageInfo_RpcPackage.Size(m)
}
func (m *RpcPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcPackage.DiscardUnknown(m)
}

var xxx_messageInfo_RpcPackage proto.InternalMessageInfo

func (m *RpcPackage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RpcPackage) GetCmd() int32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *RpcPackage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*TestMsg)(nil), "glib.TestMsg")
	proto.RegisterType((*Login)(nil), "glib.Login")
	proto.RegisterType((*AesEncode)(nil), "glib.AesEncode")
	proto.RegisterType((*AesDecode)(nil), "glib.AesDecode")
	proto.RegisterType((*AesDecodeReply)(nil), "glib.AesDecodeReply")
	proto.RegisterType((*Payload)(nil), "glib.Payload")
	proto.RegisterType((*RpcPackage)(nil), "glib.RpcPackage")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xd5, 0xa6, 0x21, 0xe4, 0x54, 0xa1, 0xca, 0x62, 0x88, 0xc4, 0x82, 0x3c, 0xb1, 0x00,
	0x42, 0x6c, 0x6c, 0x48, 0xb0, 0x20, 0x40, 0x91, 0xc5, 0x8e, 0x5c, 0xe7, 0x30, 0x51, 0x12, 0xdb,
	0x8a, 0xdb, 0xa1, 0xff, 0x1e, 0xdd, 0xc5, 0x65, 0xca, 0xd2, 0xed, 0x7b, 0xf7, 0xf2, 0xf2, 0x2e,
	0x17, 0x28, 0x87, 0x68, 0xef, 0xc2, 0xe8, 0x77, 0x5e, 0xac, 0x6c, 0xdf, 0x6e, 0x65, 0x0d, 0xc5,
	0x17, 0xc6, 0xdd, 0x47, 0xb4, 0x42, 0xc0, 0xca, 0xe9, 0x01, 0xab, 0xc5, 0xf5, 0xe2, 0xa6, 0x54,
	0xcc, 0xe2, 0x0a, 0x4a, 0xd7, 0x9a, 0xee, 0x9b, 0x8d, 0x25, 0x1b, 0xe7, 0x34, 0xf8, 0x24, 0xf3,
	0x12, 0xf2, 0xf0, 0xeb, 0x1d, 0x56, 0x19, 0x1b, 0x93, 0x90, 0xb7, 0x90, 0xbf, 0x7b, 0xdb, 0x3a,
	0xb1, 0x81, 0x6c, 0xdf, 0x36, 0xfc, 0xba, 0x5c, 0x11, 0x52, 0xc3, 0x9e, 0x46, 0x4b, 0x1e, 0x31,
	0xcb, 0x07, 0x28, 0x9f, 0x31, 0xbe, 0x3a, 0xe3, 0x1b, 0xa4, 0x48, 0x87, 0x87, 0xb4, 0x01, 0x21,
	0x45, 0x7e, 0x46, 0x3f, 0xa4, 0x6e, 0xe6, 0x14, 0x79, 0xc1, 0x13, 0x22, 0x4f, 0x70, 0xf1, 0x1f,
	0x51, 0x18, 0x7a, 0x7e, 0x8a, 0x44, 0x5a, 0x8f, 0x99, 0x3e, 0x68, 0x24, 0x33, 0x45, 0x27, 0x21,
	0xef, 0xa1, 0xa8, 0xf5, 0xa1, 0xf7, 0xba, 0x99, 0x2f, 0x0b, 0xda, 0x74, 0x9c, 0x58, 0x2b, 0x66,
	0xf9, 0x06, 0xa0, 0x82, 0xa9, 0xb5, 0xe9, 0xb4, 0x9d, 0x5b, 0x70, 0x03, 0x99, 0x19, 0x8e, 0x57,
	0x20, 0x14, 0x15, 0x14, 0x61, 0xaa, 0xe0, 0x5b, 0xae, 0xd5, 0x51, 0x6e, 0xcf, 0xf8, 0x67, 0x3d,
	0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x00, 0xfe, 0x7e, 0xb9, 0x01, 0x00, 0x00,
}
