%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.0.2

-ifndef(gw_proto).
-define(gw_proto, true).

-define(gw_proto_gpb_version, "4.0.2").

-ifndef('VERIFYREQ_PB_H').
-define('VERIFYREQ_PB_H', true).
-record('VerifyReq',
        {identity = <<>>        :: iodata() | undefined, % = 1
         channel_id = <<>>      :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('GETENTRANCEREQ_PB_H').
-define('GETENTRANCEREQ_PB_H', true).
-record('GetEntranceReq',
        {identity = <<>>        :: iodata() | undefined, % = 1
         channel_id = <<>>      :: iodata() | undefined, % = 2
         server_type = <<>>     :: iodata() | undefined, % = 3
         is_app = 0             :: integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('GETUPGRADERES_PB_H').
-define('GETUPGRADERES_PB_H', true).
-record('GetUpgradeRes',
        {server_type = <<>>     :: iodata() | undefined, % = 1
         version = <<>>         :: iodata() | undefined, % = 2
         download_url = <<>>    :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('GETENTRANCERES_PB_H').
-define('GETENTRANCERES_PB_H', true).
-record('GetEntranceRes',
        {entrace_url = <<>>     :: iodata() | undefined, % = 1
         server_type = <<>>     :: iodata() | undefined, % = 2
         server_id = <<>>       :: iodata() | undefined, % = 3
         version = <<>>         :: iodata() | undefined, % = 4
         download_url = <<>>    :: iodata() | undefined % = 5
        }).
-endif.

-ifndef('ENTERGAMERES_PB_H').
-define('ENTERGAMERES_PB_H', true).
-record('EnterGameRes',
        {code = 0               :: integer() | undefined, % = 1, 32 bits
         msg = <<>>             :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('COMMONSTATUS_PB_H').
-define('COMMONSTATUS_PB_H', true).
-record('CommonStatus',
        {code = 0               :: integer() | undefined, % = 1, 32 bits
         msg = <<>>             :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('VERIFYRES_PB_H').
-define('VERIFYRES_PB_H', true).
-record('VerifyRes',
        {code = 0               :: integer() | undefined, % = 1, 32 bits
         uid = <<>>             :: iodata() | undefined, % = 2
         msg = <<>>             :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('ENTERGAMEREQ_PB_H').
-define('ENTERGAMEREQ_PB_H', true).
-record('EnterGameReq',
        {
        }).
-endif.

-ifndef('GETUPGRADEREQ_PB_H').
-define('GETUPGRADEREQ_PB_H', true).
-record('GetUpgradeReq',
        {server_type = <<>>     :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('TESTSPEEDRES_PB_H').
-define('TESTSPEEDRES_PB_H', true).
-record('TestSpeedRes',
        {
        }).
-endif.

-ifndef('TESTSPEEDREQ_PB_H').
-define('TESTSPEEDREQ_PB_H', true).
-record('TestSpeedReq',
        {
        }).
-endif.

-endif.
