%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.0.2

-ifndef(msg_proto).
-define(msg_proto, true).

-define(msg_proto_gpb_version, "4.0.2").

-ifndef('CATCHEDFISHES_PB_H').
-define('CATCHEDFISHES_PB_H', true).
-record('CatchedFishes',
        {catchEvent = 0         :: non_neg_integer() | undefined, % = 1, 32 bits
         fishID = 0             :: non_neg_integer() | undefined, % = 2, 32 bits
         rewardID = 0           :: non_neg_integer() | undefined, % = 3, 32 bits
         lightingFishID = 0     :: non_neg_integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('UNBINDROBOTSUCCESSRES_PB_H').
-define('UNBINDROBOTSUCCESSRES_PB_H', true).
-record('UnbindRobotSuccessRes',
        {position = 0           :: non_neg_integer() | undefined, % = 1, 32 bits
         userId = <<>>          :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('GAMERECORD_PB_H').
-define('GAMERECORD_PB_H', true).
-record('GameRecord',
        {roundId = <<>>         :: iodata() | undefined, % = 1
         roomType = 0           :: integer() | undefined, % = 2, 32 bits
         allBet = 0             :: integer() | undefined, % = 3, 32 bits
         allWin = 0             :: integer() | undefined, % = 4, 32 bits
         result = 0             :: integer() | undefined, % = 5, 32 bits
         startTime = <<>>       :: iodata() | undefined, % = 6
         endTime = <<>>         :: iodata() | undefined % = 7
        }).
-endif.

-ifndef('INTOROOMREQ_PB_H').
-define('INTOROOMREQ_PB_H', true).
-record('IntoRoomReq',
        {uid = <<>>             :: iodata() | undefined, % = 1
         roomId = 0             :: non_neg_integer() | undefined, % = 2, 32 bits
         type = 0               :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('BULLETITEM_PB_H').
-define('BULLETITEM_PB_H', true).
-record('BulletItem',
        {bulletID = 0           :: non_neg_integer() | undefined, % = 1, 32 bits
         degree = 0             :: integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('FIRERES_PB_H').
-define('FIRERES_PB_H', true).
-record('FireRes',
        {bulletItemList = []    :: [#'BulletItem'{}] | undefined, % = 1
         launcherType = 0       :: non_neg_integer() | undefined, % = 2, 32 bits
         energy = 0             :: non_neg_integer() | undefined, % = 3, 32 bits
         reboundCount = 0       :: non_neg_integer() | undefined, % = 4, 32 bits
         lockFishID = 0         :: non_neg_integer() | undefined, % = 5, 32 bits
         gold = 0               :: non_neg_integer() | undefined, % = 6, 32 bits
         targetX = 0            :: non_neg_integer() | undefined, % = 7, 32 bits
         targetY = 0            :: non_neg_integer() | undefined, % = 8, 32 bits
         bulletID = 0           :: non_neg_integer() | undefined, % = 9, 32 bits
         seatID = 0             :: non_neg_integer() | undefined % = 10, 32 bits
        }).
-endif.

-ifndef('INTOROOMRES_PB_H').
-define('INTOROOMRES_PB_H', true).
-record('IntoRoomRes',
        {bTableTypeID = 0       :: integer() | undefined, % = 1, 32 bits
         backgroundImage = 0    :: integer() | undefined, % = 2, 32 bits
         launcherType = 0       :: integer() | undefined, % = 3, 32 bits
         seatID = 0             :: non_neg_integer() | undefined, % = 4, 32 bits
         rateIndex = 0          :: non_neg_integer() | undefined, % = 5, 32 bits
         match = 0              :: non_neg_integer() | undefined, % = 6, 32 bits
         matchGold = 0          :: non_neg_integer() | undefined, % = 7, 32 bits
         minRate = 0            :: non_neg_integer() | undefined, % = 8, 32 bits
         maxRate = 0            :: non_neg_integer() | undefined, % = 9, 32 bits
         roomId = 0             :: non_neg_integer() | undefined, % = 10, 32 bits
         roomName = <<>>        :: iodata() | undefined, % = 11
         endTime = 0            :: non_neg_integer() | undefined % = 12, 32 bits
        }).
-endif.

-ifndef('COMMONSTATUS_PB_H').
-define('COMMONSTATUS_PB_H', true).
-record('CommonStatus',
        {code = 0               :: integer() | undefined, % = 1, 32 bits
         msg = <<>>             :: iodata() | undefined, % = 2
         type = 0               :: integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('BINDROBOTREQ_PB_H').
-define('BINDROBOTREQ_PB_H', true).
-record('BindRobotReq',
        {position = 0           :: non_neg_integer() | undefined, % = 1, 32 bits
         userId = <<>>          :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('UNBINDROBOTREQ_PB_H').
-define('UNBINDROBOTREQ_PB_H', true).
-record('UnbindRobotReq',
        {position = 0           :: non_neg_integer() | undefined, % = 1, 32 bits
         userId = <<>>          :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('CHANGECLIENTRATEREQ_PB_H').
-define('CHANGECLIENTRATEREQ_PB_H', true).
-record('ChangeClientRateReq',
        {opt = 0                :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('ROOMINFOREQ_PB_H').
-define('ROOMINFOREQ_PB_H', true).
-record('RoomInfoReq',
        {type = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         uid = <<>>             :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('ROOMONLINEINFO_PB_H').
-define('ROOMONLINEINFO_PB_H', true).
-record('RoomOnlineInfo',
        {type = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         playCount = 0          :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('ROOMONLINEINFORES_PB_H').
-define('ROOMONLINEINFORES_PB_H', true).
-record('RoomOnlineInfoRes',
        {roomOnlineInfo = []    :: [#'RoomOnlineInfo'{}] | undefined % = 1
        }).
-endif.

-ifndef('GAMERECORDRES_PB_H').
-define('GAMERECORDRES_PB_H', true).
-record('GameRecordRes',
        {gameRecord = []        :: [#'GameRecord'{}] | undefined % = 1
        }).
-endif.

-ifndef('LOGINREQ_PB_H').
-define('LOGINREQ_PB_H', true).
-record('LoginReq',
        {identity = <<>>        :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('BROADCASTMESSAGE_PB_H').
-define('BROADCASTMESSAGE_PB_H', true).
-record('BroadcastMessage',
        {broadType = 0          :: non_neg_integer() | undefined, % = 1, 32 bits
         msg = <<>>             :: iodata() | undefined, % = 2
         langId = 0             :: non_neg_integer() | undefined, % = 3, 32 bits
         params = []            :: [iodata()] | undefined, % = 4
         priority = 0           :: non_neg_integer() | undefined % = 5, 32 bits
        }).
-endif.

-ifndef('BROADCASTMESSAGELIST_PB_H').
-define('BROADCASTMESSAGELIST_PB_H', true).
-record('BroadcastMessageList',
        {messageList = []       :: [#'BroadcastMessage'{}] | undefined % = 1
        }).
-endif.

-ifndef('MSG_PB_H').
-define('MSG_PB_H', true).
-record('Msg',
        {action = 0             :: non_neg_integer() | undefined, % = 1, 32 bits
         msgBody = <<>>         :: binary() | undefined, % = 2
         token = <<>>           :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('LEAVEGAMEREQ_PB_H').
-define('LEAVEGAMEREQ_PB_H', true).
-record('LeaveGameReq',
        {type = 0               :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('FIREREQ_PB_H').
-define('FIREREQ_PB_H', true).
-record('FireReq',
        {degree = 0             :: integer() | undefined, % = 1, 32 bits
         lockedFishID = 0       :: non_neg_integer() | undefined, % = 2, 32 bits
         bulletID = 0           :: non_neg_integer() | undefined, % = 3, 32 bits
         targetX = 0            :: non_neg_integer() | undefined, % = 4, 32 bits
         targetY = 0            :: non_neg_integer() | undefined % = 5, 32 bits
        }).
-endif.

-ifndef('MSGS_PB_H').
-define('MSGS_PB_H', true).
-record('Msgs',
        {msgList = []           :: [#'Msg'{}] | undefined % = 1
        }).
-endif.

-ifndef('NOTIFYLEAVEGAMERES_PB_H').
-define('NOTIFYLEAVEGAMERES_PB_H', true).
-record('NotifyLeaveGameRes',
        {seatID = 0             :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('CATCHEDFISHREQ_PB_H').
-define('CATCHEDFISHREQ_PB_H', true).
-record('CatchedFishReq',
        {userId = <<>>          :: iodata() | undefined, % = 1
         fishID = 0             :: non_neg_integer() | undefined, % = 2, 32 bits
         bulletID = 0           :: non_neg_integer() | undefined, % = 3, 32 bits
         catchedFishs = []      :: [non_neg_integer()] | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('NOTIFYENTERGAMERES_PB_H').
-define('NOTIFYENTERGAMERES_PB_H', true).
-record('NotifyEnterGameRes',
        {uid = <<>>             :: iodata() | undefined, % = 1
         name = <<>>            :: iodata() | undefined, % = 2
         headUrl = <<>>         :: iodata() | undefined, % = 3
         ip = <<>>              :: iodata() | undefined, % = 4
         money = 0.0            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 5
         bangMoney = 0.0        :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 6
         launcherType = 0       :: non_neg_integer() | undefined, % = 7, 32 bits
         rateIndex = 0          :: non_neg_integer() | undefined, % = 8, 32 bits
         energy = 0             :: non_neg_integer() | undefined, % = 9, 32 bits
         seat = 0               :: non_neg_integer() | undefined, % = 10, 32 bits
         roomCard = 0           :: non_neg_integer() | undefined % = 11, 32 bits
        }).
-endif.

-ifndef('CHANGECLIENTRATERES_PB_H').
-define('CHANGECLIENTRATERES_PB_H', true).
-record('ChangeClientRateRes',
        {seatID = 0             :: non_neg_integer() | undefined, % = 1, 32 bits
         isCanUseRate = 0       :: non_neg_integer() | undefined, % = 2, 32 bits
         rateIndex = 0          :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('CHANGECLIENTRATETYPEREQ_PB_H').
-define('CHANGECLIENTRATETYPEREQ_PB_H', true).
-record('ChangeClientRateTypeReq',
        {seatID = 0             :: non_neg_integer() | undefined, % = 1, 32 bits
         rateIndex = 0          :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('ADDFISHES_PB_H').
-define('ADDFISHES_PB_H', true).
-record('AddFishes',
        {groupID = 0            :: non_neg_integer() | undefined, % = 1, 32 bits
         pathID = 0             :: non_neg_integer() | undefined, % = 2, 32 bits
         startID = 0            :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('CHANGELAUNCHERREQ_PB_H').
-define('CHANGELAUNCHERREQ_PB_H', true).
-record('ChangeLauncherReq',
        {seatID = 0             :: non_neg_integer() | undefined, % = 1, 32 bits
         launcherType = 0       :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('GAMERECORDREQ_PB_H').
-define('GAMERECORDREQ_PB_H', true).
-record('GameRecordReq',
        {
        }).
-endif.

-ifndef('BINDROBOTSUCCESSRES_PB_H').
-define('BINDROBOTSUCCESSRES_PB_H', true).
-record('BindRobotSuccessRes',
        {position = 0           :: non_neg_integer() | undefined, % = 1, 32 bits
         userId = <<>>          :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('CHANGELAUNCHERRES_PB_H').
-define('CHANGELAUNCHERRES_PB_H', true).
-record('ChangeLauncherRes',
        {seatID = 0             :: non_neg_integer() | undefined, % = 1, 32 bits
         launcherType = 0       :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('ROOMINFORES_PB_H').
-define('ROOMINFORES_PB_H', true).
-record('RoomInfoRes',
        {enterKindId = 0        :: non_neg_integer() | undefined, % = 1, 32 bits
         gameType = 0           :: non_neg_integer() | undefined, % = 2, 32 bits
         enterKindServerId = <<>> :: iodata() | undefined, % = 3
         enterKindPost = 0      :: non_neg_integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('CATCHEDFISHRES_PB_H').
-define('CATCHEDFISHRES_PB_H', true).
-record('CatchedFishRes',
        {bulletID = 0           :: non_neg_integer() | undefined, % = 1, 32 bits
         gold = 0               :: non_neg_integer() | undefined, % = 2, 32 bits
         isRemoveBullet = 0     :: non_neg_integer() | undefined, % = 3, 32 bits
         totalNum = 0.0         :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4
         seatID = 0             :: non_neg_integer() | undefined, % = 5, 32 bits
         catchedFishes = []     :: [#'CatchedFishes'{}] | undefined % = 6
        }).
-endif.

-ifndef('LEAVEGAMERES_PB_H').
-define('LEAVEGAMERES_PB_H', true).
-record('LeaveGameRes',
        {code = 0               :: integer() | undefined, % = 1, 32 bits
         msg = <<>>             :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('SYNCFISHDATA_PB_H').
-define('SYNCFISHDATA_PB_H', true).
-record('SyncFishData',
        {fishID = 0             :: non_neg_integer() | undefined, % = 1, 32 bits
         groupID = 0            :: non_neg_integer() | undefined, % = 2, 32 bits
         fishTime = 0.0         :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
         pathGroup = 0          :: non_neg_integer() | undefined, % = 4, 32 bits
         pathIdx = 0            :: non_neg_integer() | undefined, % = 5, 32 bits
         isActiveEvent = false  :: boolean() | 0 | 1 | undefined, % = 6
         elapsedTime = 0        :: non_neg_integer() | undefined, % = 7, 32 bits
         package = 0            :: non_neg_integer() | undefined, % = 8, 32 bits
         specialType = 0        :: non_neg_integer() | undefined, % = 9, 32 bits
         delayScaling = 0       :: non_neg_integer() | undefined, % = 10, 32 bits
         delayDuration1 = 0     :: non_neg_integer() | undefined, % = 11, 32 bits
         delayDuration2 = 0     :: non_neg_integer() | undefined, % = 12, 32 bits
         delayDuration3 = 0     :: non_neg_integer() | undefined, % = 13, 32 bits
         delayCurrentTime = 0   :: non_neg_integer() | undefined % = 14, 32 bits
        }).
-endif.

-ifndef('SYNCFISHES_PB_H').
-define('SYNCFISHES_PB_H', true).
-record('SyncFishes',
        {fishList = []          :: [#'SyncFishData'{}] | undefined % = 1
        }).
-endif.

-ifndef('NOTIFYSTATE_PB_H').
-define('NOTIFYSTATE_PB_H', true).
-record('NotifyState',
        {seatID = 0             :: non_neg_integer() | undefined, % = 1, 32 bits
         money = 0              :: non_neg_integer() | undefined, % = 2, 32 bits
         bangMoney = 0          :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('ITEMDATA_PB_H').
-define('ITEMDATA_PB_H', true).
-record('ItemData',
        {itemId = 0             :: non_neg_integer() | undefined, % = 1, 32 bits
         count = 0              :: non_neg_integer() | undefined, % = 2, 32 bits
         expried = 0            :: integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('LOGINRES_PB_H').
-define('LOGINRES_PB_H', true).
-record('LoginRes',
        {uid = <<>>             :: iodata() | undefined, % = 1
         name = <<>>            :: iodata() | undefined, % = 2
         headUrl = <<>>         :: iodata() | undefined, % = 3
         ip = <<>>              :: iodata() | undefined, % = 4
         money = 0              :: non_neg_integer() | undefined, % = 5, 32 bits
         bangMoney = 0.0        :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 6
         bankMoney = 0.0        :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 7
         bankPassword = <<>>    :: iodata() | undefined, % = 8
         telephone_fare = 0     :: non_neg_integer() | undefined, % = 9, 32 bits
         serverTime = 0         :: non_neg_integer() | undefined, % = 10, 32 bits
         vipExp = 0             :: non_neg_integer() | undefined, % = 11, 32 bits
         phoneNum = <<>>        :: iodata() | undefined, % = 12
         roomCard = 0           :: non_neg_integer() | undefined, % = 13, 32 bits
         token = <<>>           :: iodata() | undefined % = 14
        }).
-endif.

-ifndef('HEARTBEAT_PB_H').
-define('HEARTBEAT_PB_H', true).
-record('Heartbeat',
        {
        }).
-endif.

-ifndef('CLEARSCENERES_PB_H').
-define('CLEARSCENERES_PB_H', true).
-record('ClearSceneRes',
        {clearType = 0          :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-endif.
