[package]
name = "redisc"
version = "0.1.0"
authors = ["maomao <5622876@qq.com>"]

[dependencies]
r2d2_redis = "0.8.0"
singleton = "0.2.2"
tini = "0.2.0"

log = "0.4.6"

sys_config={path = "../sys_config"}