[package]
name = "mysql_demo"
version = "0.1.0"
authors = ["maomao <you@example.com>"]

[dependencies]
r2d2 = "*"
diesel = { version = "*", features = ["mysql"] }
diesel_codegen = { version = "*", features = ["mysql"] }
r2d2-diesel = "*"
dotenv="0.10"