[package]
name = "chat"
version = "0.1.0"
authors = ["maomao <you@example.com>"]

[dependencies]

rand = "0.3"
bytes = "0.4"
byteorder = "1.1"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

actix = "0.5.1"