%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(inner_msg_proto).
-define(inner_msg_proto, true).

-define(inner_msg_proto_gpb_version, "3.26.4").

-ifndef('INNERLOGIN_PB_H').
-define('INNERLOGIN_PB_H', true).
-record('InnerLogin',
        {user_id                :: integer(),       % = 1, 32 bits
         token                  :: binary() | iolist(), % = 2
         proxy_id               :: integer(),       % = 3, 32 bits
         ip                     :: binary() | iolist(), % = 4
         login_time             :: integer()        % = 5, 32 bits
        }).
-endif.

-ifndef('INNERLOGINREPLY_PB_H').
-define('INNERLOGINREPLY_PB_H', true).
-record('InnerLoginReply',
        {user_id                :: integer(),       % = 1, 32 bits
         error_type             :: integer(),       % = 2, 32 bits
         msg                    :: binary() | iolist() % = 3
        }).
-endif.

-ifndef('INNERREGISTPROXY_PB_H').
-define('INNERREGISTPROXY_PB_H', true).
-record('InnerRegistProxy',
        {id                     :: integer(),       % = 1, 32 bits
         ip                     :: binary() | iolist(), % = 2
         port                   :: integer()        % = 3, 32 bits
        }).
-endif.

-ifndef('INNERLOGOUT_PB_H').
-define('INNERLOGOUT_PB_H', true).
-record('InnerLogout',
        {user_id                :: integer(),       % = 1, 32 bits
         token                  :: binary() | iolist(), % = 2
         proxy_id               :: integer()        % = 3, 32 bits
        }).
-endif.

-ifndef('INNERSYNCCLIENTS_PB_H').
-define('INNERSYNCCLIENTS_PB_H', true).
-record('InnerSyncClients',
        {clients = []           :: [#'InnerLogin'{}] % = 1
        }).
-endif.

-endif.
