%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(msg_types).

-include("msg_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('Message') ->
  {struct, [{1, i64},
          {2, string}]}
;

struct_info('UserInfo') ->
  {struct, [{1, i64},
          {2, string}]}
;

struct_info('ServerReply') ->
  {struct, [{1, i64},
          {2, string}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('Message') ->
  {struct, [{1, undefined, i64, 'id', undefined},
          {2, undefined, string, 'text', undefined}]}
;

struct_info_ext('UserInfo') ->
  {struct, [{1, undefined, i64, 'uid', undefined},
          {2, undefined, string, 'name', undefined}]}
;

struct_info_ext('ServerReply') ->
  {struct, [{1, undefined, i64, 'code', undefined},
          {2, undefined, string, 'text', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

