[package]
name = "tcp_echo"
version = "0.1.0"
authors = ["mao <5622876@qq.com>"]

[dependencies]
tokio-proto = { git = "https://github.com/tokio-rs/tokio-proto" }
tokio-core = "0.1.10"
tokio-io = "0.1.3"
futures = "0.1.16"
tokio-service = "0.1.0"
bytes = "0.4.5"