[package]
name = "glib"
version = "0.1.0"
authors = ["maomao <5622876@qq.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
byteorder = "1.1"

protobuf = "2.2.0"

[build-dependencies]
protobuf-codegen-pure = "2.2.0"