[package]
name = "pb_package"
version = "0.1.0"
authors = ["maomao <5622876@qq.com>"]


[dependencies]
protobuf = "2.2.0"
byteorder = "1.1"
log = "0.4.6"
easy-logging = "*"

[build-dependencies]
protobuf-codegen-pure = "2.2.0"
