[package]
name = "mysqlc"
version = "0.1.0"
authors = ["maomao <5622876@qq.com>"]

[dependencies]
r2d2 = "0.8.3"
diesel = { version = "1.3.3", features = ["mysql"] }
diesel_codegen = { version = "0.16.1", features = ["mysql"] }
r2d2-diesel = "1.0.0"
dotenv="0.10"

singleton = "0.2.2"
