// This file is generated by rust-protobuf 2.2.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct TestMsg {
    // message fields
    pub f1: ::std::string::String,
    pub f2: ::std::string::String,
    pub f3: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl TestMsg {
    pub fn new() -> TestMsg {
        ::std::default::Default::default()
    }

    // string f1 = 1;

    pub fn clear_f1(&mut self) {
        self.f1.clear();
    }

    // Param is passed by value, moved
    pub fn set_f1(&mut self, v: ::std::string::String) {
        self.f1 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_f1(&mut self) -> &mut ::std::string::String {
        &mut self.f1
    }

    // Take field
    pub fn take_f1(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.f1, ::std::string::String::new())
    }

    pub fn get_f1(&self) -> &str {
        &self.f1
    }

    // string f2 = 2;

    pub fn clear_f2(&mut self) {
        self.f2.clear();
    }

    // Param is passed by value, moved
    pub fn set_f2(&mut self, v: ::std::string::String) {
        self.f2 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_f2(&mut self) -> &mut ::std::string::String {
        &mut self.f2
    }

    // Take field
    pub fn take_f2(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.f2, ::std::string::String::new())
    }

    pub fn get_f2(&self) -> &str {
        &self.f2
    }

    // string f3 = 3;

    pub fn clear_f3(&mut self) {
        self.f3.clear();
    }

    // Param is passed by value, moved
    pub fn set_f3(&mut self, v: ::std::string::String) {
        self.f3 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_f3(&mut self) -> &mut ::std::string::String {
        &mut self.f3
    }

    // Take field
    pub fn take_f3(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.f3, ::std::string::String::new())
    }

    pub fn get_f3(&self) -> &str {
        &self.f3
    }
}

impl ::protobuf::Message for TestMsg {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.f1)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.f2)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.f3)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.f1.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.f1);
        }
        if !self.f2.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.f2);
        }
        if !self.f3.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.f3);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.f1.is_empty() {
            os.write_string(1, &self.f1)?;
        }
        if !self.f2.is_empty() {
            os.write_string(2, &self.f2)?;
        }
        if !self.f3.is_empty() {
            os.write_string(3, &self.f3)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TestMsg {
        TestMsg::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "f1",
                    |m: &TestMsg| { &m.f1 },
                    |m: &mut TestMsg| { &mut m.f1 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "f2",
                    |m: &TestMsg| { &m.f2 },
                    |m: &mut TestMsg| { &mut m.f2 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "f3",
                    |m: &TestMsg| { &m.f3 },
                    |m: &mut TestMsg| { &mut m.f3 },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<TestMsg>(
                    "TestMsg",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static TestMsg {
        static mut instance: ::protobuf::lazy::Lazy<TestMsg> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const TestMsg,
        };
        unsafe {
            instance.get(TestMsg::new)
        }
    }
}

impl ::protobuf::Clear for TestMsg {
    fn clear(&mut self) {
        self.clear_f1();
        self.clear_f2();
        self.clear_f3();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TestMsg {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestMsg {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x07a.proto\x12\x03AAA\"9\n\x07TestMsg\x12\x0e\n\x02f1\x18\x01\x20\x01\
    (\tB\x02\x18\0\x12\x0e\n\x02f2\x18\x02\x20\x01(\tB\x02\x18\0\x12\x0e\n\
    \x02f3\x18\x03\x20\x01(\tB\x02\x18\0B\0b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
