run:
	rebar3 shell --name erl_test@127.0.0.1 --setcookie erl_test

# test:
# 	rebar3 eunit

test:
	rebar3 ct
# stop:
# 	ps -efww|grep xgn.node|grep -v grep|cut -c 9-15|xargs kill -9

push:
	git add .
	git commit -m 'pu'
	git push

# ps:
# 	ps aux | grep xgn.node


