%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.0.2

-ifndef(hello_proto).
-define(hello_proto, true).

-define(hello_proto_gpb_version, "4.0.2").

-ifndef('HELLO_PB_H').
-define('HELLO_PB_H', true).
-record('Hello',
        {name                   :: iodata()         % = 1
        }).
-endif.

-endif.
